-- MySQL Script generated by MySQL Workbench
-- Sun Jan  5 10:46:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fsraiDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fsraiDatabase` ;

-- -----------------------------------------------------
-- Schema fsraiDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fsraiDatabase` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema fsraidatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fsraidatabase` ;

-- -----------------------------------------------------
-- Schema fsraidatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fsraidatabase` ;
USE `fsraiDatabase` ;

-- -----------------------------------------------------
-- Table `fsraiDatabase`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`ROLE` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `NAME` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC));


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`USER` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `FIRSTNAME` VARCHAR(21) NOT NULL,
  `LASTNAME` VARCHAR(24) NOT NULL,
  `DATE_OF_BIRTH` DATE NOT NULL,
  `DESCRIPTION` TEXT NULL,
  `PICTURE` VARCHAR(28) NULL,
  `EMAIL` VARCHAR(62) NOT NULL,
  `PASSWORD` VARCHAR(60) NOT NULL,
  `ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_USER_ROLE1_idx` (`ROLE_ID` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC),
  CONSTRAINT `fk_USER_ROLE1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `fsraiDatabase`.`ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`FUNCTION_FSR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`FUNCTION_FSR` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`FUNCTION_FSR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC));


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`MEMBER_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`MEMBER_HISTORY` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`MEMBER_HISTORY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `START_DATE` DATE NOT NULL,
  `END_DATE` DATE NULL,
  `MEMBER_ID` INT NOT NULL,
  `FUNCTION_FSR_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MEMBER_HISTORY_MEMBER1_idx` (`MEMBER_ID` ASC),
  INDEX `fk_MEMBER_HISTORY_FUNCTION_FSR1_idx` (`FUNCTION_FSR_ID` ASC),
  CONSTRAINT `fk_MEMBER_HISTORY_MEMBER1`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `fsraiDatabase`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEMBER_HISTORY_FUNCTION_FSR1`
    FOREIGN KEY (`FUNCTION_FSR_ID`)
    REFERENCES `fsraiDatabase`.`FUNCTION_FSR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`LOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`LOCATION` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`LOCATION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `STREET` VARCHAR(50) NOT NULL,
  `NUMBER` VARCHAR(5) NOT NULL,
  `ZIPCODE` VARCHAR(5) NOT NULL,
  `CITY` VARCHAR(58) NOT NULL,
  `ROOM` VARCHAR(9) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`EVENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`EVENT` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`EVENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `NAME` VARCHAR(64) NOT NULL,
  `DATE` DATE NOT NULL,
  `DESCRIPTION` TEXT NOT NULL,
  `PICTURE` VARCHAR(29) NULL,
  `LOCATION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_EVENTS_LOCATION1_idx` (`LOCATION_ID` ASC),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC),
  CONSTRAINT `fk_EVENTS_LOCATION1`
    FOREIGN KEY (`LOCATION_ID`)
    REFERENCES `fsraiDatabase`.`LOCATION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`BOOKING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`BOOKING` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`BOOKING` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `EVENT_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_REGISTRATION_EVENTS1_idx` (`EVENT_ID` ASC),
  INDEX `fk_REGISTRATION_MEMBER1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_REGISTRATION_EVENTS1`
    FOREIGN KEY (`EVENT_ID`)
    REFERENCES `fsraiDatabase`.`EVENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REGISTRATION_MEMBER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `fsraiDatabase`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `fsraidatabase` ;
USE `fsraiDatabase` ;

-- -----------------------------------------------------
-- Placeholder table for view `fsraidatabase`.`geteventinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsraidatabase`.`geteventinfo` (`ID` INT, `NAME` INT, `DATE` INT, `DESCRIPTION` INT, `PICTURE` INT, `LOCATION_ID` INT, `CREATED_AT` INT, `STREET` INT, `NUMBER` INT, `ZIPCODE` INT, `CITY` INT, `ROOM` INT);

-- -----------------------------------------------------
-- Placeholder table for view `fsraidatabase`.`getUserMemberHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsraidatabase`.`getUserMemberHistory` (`ID` INT, `START_DATE` INT, `END_DATE` INT, `MEMBER_ID` INT, `FUNCTION_FSR_ID` INT, `FIRSTNAME` INT, `LASTNAME` INT, `DATE_OF_BIRTH` INT, `DESCRIPTION` INT, `PICTURE` INT, `EMAIL` INT, `ROLE_ID` INT);

-- -----------------------------------------------------
-- View `fsraidatabase`.`geteventinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraidatabase`.`geteventinfo`;
DROP VIEW IF EXISTS `fsraidatabase`.`geteventinfo` ;
USE `fsraidatabase`;
create  OR REPLACE definer = root@localhost view fsraidatabase.geteventinfo as select `e`.`ID`          AS `ID`,
       `e`.`NAME`        AS `NAME`,
       `e`.`DATE`        AS `DATE`,
       `e`.`DESCRIPTION` AS `DESCRIPTION`,
       `e`.`PICTURE`     AS `PICTURE`,
       `e`.`LOCATION_ID` AS `LOCATION_ID`,
       `e`.`CREATED_AT`  AS `CREATED_AT`,
       `l`.`STREET`      AS `STREET`,
       `l`.`NUMBER`      AS `NUMBER`,
       `l`.`ZIPCODE`     AS `ZIPCODE`,
       `l`.`CITY`        AS `CITY`,
       `l`.`ROOM`        AS `ROOM`
from (`fsraidatabase`.`event` `e`
         join `fsraidatabase`.`location` `l` on ((`e`.`LOCATION_ID` = `l`.`ID`)));

-- -----------------------------------------------------
-- View `fsraidatabase`.`getUserMemberHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraidatabase`.`getUserMemberHistory`;
DROP VIEW IF EXISTS `fsraidatabase`.`getUserMemberHistory` ;
USE `fsraidatabase`;
CREATE 
     OR REPLACE DEFINER = root@localhost 
VIEW fsraidatabase.getUserMemberHistory AS
    SELECT 
        `mh`.`ID` AS `ID`,
        `mh`.`START_DATE` AS `START_DATE`,
        `mh`.`END_DATE` AS `END_DATE`,
        `mh`.`MEMBER_ID` AS `MEMBER_ID`,
        `mh`.`FUNCTION_FSR_ID` AS `FUNCTION_FSR_ID`,
        `u`.`FIRSTNAME` AS `FIRSTNAME`,
        `u`.`LASTNAME` AS `LASTNAME`,
        `u`.`DATE_OF_BIRTH` AS `DATE_OF_BIRTH`,
        `u`.`DESCRIPTION` AS `DESCRIPTION`,
        `u`.`PICTURE` AS `PICTURE`,
        `u`.`EMAIL` AS `EMAIL`,
        `u`.`ROLE_ID` AS `ROLE_ID`
        
    FROM
        (`fsraidatabase`.`member_history` `mh`
        JOIN `fsraidatabase`.`user` `u` ON ((`mh`.`MEMBER_ID` = `u`.`ID`)));

-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`ROLE`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`ROLE` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Administrator');
INSERT INTO `fsraiDatabase`.`ROLE` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Mitglied');
INSERT INTO `fsraiDatabase`.`ROLE` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Nutzer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Danny', 'Steinbrecher', '1989-12-24', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil2.jpg', 'danny.steinbrecher@fh-erfurt.de', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 1);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Niclas', 'Jarowsky', '2000-01-01', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil2.jpg', 'niclas.jarowsky@fh-erfurt.de', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 1);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Anton', 'Bespablov', '2000-01-01', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil3.jpg', 'anton.bespablov@fh-erfurt.de', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 2);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Frieder', 'Ullmann', '2000-01-01', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil4.jpg', 'frieder.ullmann@fh-erfurt.de', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 2);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Torsten', 'Petersen', '2000-01-01', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil5.jpg', 'torsten.petersen@outlook.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Admin', 'Chef', '2000-01-01', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil6.jpg', 'admin@fh', '$2y$13$wLzUPkMmy1dKw3mVj183leJpb7YMTM9W0TYt7.FJg3C06UpbeTxZy', 1);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Mitglied', 'Horst', '2000-01-01', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil7.jpg', 'mitglied@fh', '$2y$13$RaN6GQlQ5eJi9rm4BeDdfOewonDkN3/DnpRMVRElJGcgXYRCocDEa', 2);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Nutzer', 'Noob', '2000-01-01', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil8.jpg', 'nutzer@fh', '$2y$13$QEAbCyo5glD61CzkEQpmF.7jJCW7Kl2nvi62qhGVjKUvFxiCXbeV.', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Quintessa', 'Alvarado', '1986-01-28', NULL, NULL, 'urna.Nullam.lobortis@scelerisque.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Devin', 'Bryant', '1996-01-10', NULL, NULL, 'et@tristiquesenectus.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Scarlett', 'Mcdowell', '1991-10-09', NULL, NULL, 'Donec.dignissim@orciadipiscingnon.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Winter', 'Lamb', '1993-06-07', NULL, NULL, 'egestas.ligula@at.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Joseph', 'Cooper', '1987-05-31', NULL, NULL, 'In.condimentum.Donec@turpis.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Moana', 'Mccoy', '2000-05-21', NULL, NULL, 'Aliquam@eusemPellentesque.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Walker', 'Molina', '1989-03-02', NULL, NULL, 'orci.tincidunt.adipiscing@anteiaculis.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Carly', 'Jensen', '1992-11-19', NULL, NULL, 'interdum.Sed@necquamCurabitur.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'McKenzie', 'Cunningham', '1994-03-19', NULL, NULL, 'vestibulum.massa.rutrum@felis.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Celeste', 'Mcneil', '2004-07-22', NULL, NULL, 'ut@sed.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Fiona', 'Conrad', '2000-02-01', NULL, NULL, 'sit@vestibulumnequesed.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Harlan', 'Cannon', '1988-11-21', NULL, NULL, 'egestas.Aliquam@vulputate.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Ronan', 'Wall', '1986-01-24', NULL, NULL, 'molestie@idliberoDonec.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Zephr', 'Marks', '1998-04-13', NULL, NULL, 'sit.amet@scelerisquescelerisque.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Hakeem', 'Carlson', '2001-12-24', NULL, NULL, 'hendrerit.neque@neque.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Cailin', 'Carney', '1996-12-30', NULL, NULL, 'accumsan.interdum.libero@etarcu.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Abigail', 'Lynn', '1992-12-21', NULL, NULL, 'convallis.erat@molestie.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Amir', 'Vasquez', '2001-08-31', NULL, NULL, 'mattis.velit.justo@Aenean.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Giacomo', 'Rogers', '1989-05-29', NULL, NULL, 'tristique.ac@malesuadafamesac.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Colby', 'Barnes', '2004-09-15', NULL, NULL, 'Cras.vehicula@viverraDonectempus.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Octavia', 'Walter', '2003-06-05', NULL, NULL, 'Etiam@magna.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Scarlett', 'Knight', '1995-04-16', NULL, NULL, 'pede.Cras@mus.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kirby', 'Trujillo', '2004-02-11', NULL, NULL, 'fringilla@tinciduntDonecvitae.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kyra', 'Frye', '1985-01-19', NULL, NULL, 'Curae.Donec.tincidunt@risus.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Lois', 'Molina', '1990-08-20', NULL, NULL, 'aliquet.sem.ut@velesttempor.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Amal', 'Suarez', '2003-02-09', NULL, NULL, 'vehicula.Pellentesque@Vestibulumante.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Whoopi', 'Wiggins', '1991-07-27', NULL, NULL, 'dolor.elit.pellentesque@condimentumegetvolutpat.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Finn', 'Miranda', '1984-06-27', NULL, NULL, 'diam.lorem@pellentesque.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Elmo', 'Neal', '1987-06-12', NULL, NULL, 'eu.erat@Sed.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Phillip', 'Stokes', '2003-12-02', NULL, NULL, 'mollis.nec@Vestibulumanteipsum.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Tanya', 'Wooten', '1995-05-23', NULL, NULL, 'sociis.natoque@Suspendissealiquet.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Rhoda', 'Gibbs', '1994-10-30', NULL, NULL, 'elit.pharetra@porttitortellus.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Malachi', 'Cross', '2004-11-21', NULL, NULL, 'aliquet@Sed.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Aline', 'Henson', '2001-03-12', NULL, NULL, 'vel.venenatis.vel@placeratCrasdictum.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Maryam', 'Osborne', '1997-03-04', NULL, NULL, 'in@purus.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Bradley', 'Delacruz', '1987-01-26', NULL, NULL, 'Integer@ullamcorper.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Joshua', 'Finch', '1986-03-10', NULL, NULL, 'massa.lobortis.ultrices@nectempusscelerisque.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Graiden', 'Wilkinson', '1990-03-08', NULL, NULL, 'montes.nascetur@Donec.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Vera', 'Wright', '1990-11-18', NULL, NULL, 'Phasellus.dolor@sit.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Jenna', 'Valenzuela', '1990-10-10', NULL, NULL, 'est.Mauris.eu@fringilla.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Moana', 'Gonzales', '1997-07-19', NULL, NULL, 'eu@egestasascelerisque.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Rafael', 'Arnold', '2005-09-30', NULL, NULL, 'magna.a@neque.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Maggie', 'Wallace', '1997-01-31', NULL, NULL, 'erat@non.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Dominique', 'Roman', '2001-04-24', NULL, NULL, 'tortor.nibh@Naminterdumenim.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Merritt', 'Olsen', '1997-01-09', NULL, NULL, 'Nunc.quis@In.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Wing', 'Foster', '1984-03-30', NULL, NULL, 'quis.diam@iaculis.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Dustin', 'Decker', '2002-04-16', NULL, NULL, 'a.enim@lobortisauguescelerisque.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Orlando', 'Barr', '1986-06-11', NULL, NULL, 'Nullam.enim@ipsumnuncid.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Emerson', 'Parsons', '1997-08-16', NULL, NULL, 'Curae.Phasellus@nequesed.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kimberly', 'Lyons', '1989-08-02', NULL, NULL, 'malesuada@antedictummi.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Benjamin', 'Gillespie', '1998-11-21', NULL, NULL, 'sed@sem.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Brandon', 'Rodgers', '1993-11-29', NULL, NULL, 'sit.amet@feugiat.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Aretha', 'Casey', '1991-09-17', NULL, NULL, 'turpis.vitae.purus@aliquetsem.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Catherine', 'Summers', '1990-07-04', NULL, NULL, 'et@sem.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Lillith', 'Whitney', '1984-02-18', NULL, NULL, 'Nunc@eleifendCrassed.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Craig', 'Banks', '1992-09-01', NULL, NULL, 'in.dolor@sitametfaucibus.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Ignatius', 'Parrish', '1993-04-02', NULL, NULL, 'pellentesque.massa@luctus.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Bethany', 'Donaldson', '1991-03-20', NULL, NULL, 'ultrices@arcuVestibulumut.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Grace', 'Weeks', '1997-11-12', NULL, NULL, 'Maecenas.malesuada.fringilla@montesnascetur.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Marcia', 'Wise', '1986-03-20', NULL, NULL, 'tellus.lorem@eratnequenon.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Frances', 'Blair', '1993-08-18', NULL, NULL, 'Sed.nulla@felisDonectempor.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Athena', 'Crane', '1988-04-23', NULL, NULL, 'sit.amet.risus@feugiatplaceratvelit.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Joshua', 'Moody', '1987-05-07', NULL, NULL, 'ante.dictum.mi@Vestibulumanteipsum.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Jessamine', 'Slater', '1993-08-23', NULL, NULL, 'urna@semutcursus.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Grady', 'Mcdaniel', '2004-08-22', NULL, NULL, 'felis.adipiscing@inaliquet.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Camille', 'Carver', '1997-05-18', NULL, NULL, 'a@Cumsociis.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Noelle', 'Parrish', '1995-10-20', NULL, NULL, 'non@erat.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'April', 'Middleton', '1988-02-20', NULL, NULL, 'purus.mauris.a@nislNullaeu.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Gray', 'Casey', '1987-11-22', NULL, NULL, 'molestie@sapien.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Myles', 'Bender', '1998-12-14', NULL, NULL, 'malesuada.fames@eleifendnondapibus.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kasper', 'Rogers', '1986-01-12', NULL, NULL, 'ligula.Aenean.euismod@molestieSedid.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kareem', 'Hickman', '1991-10-30', NULL, NULL, 'neque.pellentesque.massa@litoratorquentper.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Silas', 'Barber', '1992-12-24', NULL, NULL, 'vitae@sed.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Indigo', 'Carlson', '1997-12-04', NULL, NULL, 'sed.tortor@Sed.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Stewart', 'Flores', '1984-12-13', NULL, NULL, 'interdum@Pellentesquehabitant.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Karyn', 'Murray', '2002-10-07', NULL, NULL, 'tempor@ataugueid.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Rana', 'Hodge', '1985-10-20', NULL, NULL, 'eget.mollis.lectus@Sednulla.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Byron', 'Dillon', '1991-10-29', NULL, NULL, 'ipsum.primis.in@euligulaAenean.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Maxwell', 'Puckett', '1992-03-24', NULL, NULL, 'massa@malesuada.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Stewart', 'Zamora', '1997-09-23', NULL, NULL, 'eu.sem.Pellentesque@faucibus.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kitra', 'Cochran', '1997-01-17', NULL, NULL, 'mus@Maecenas.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Lois', 'Blake', '1989-10-09', NULL, NULL, 'auctor.vitae.aliquet@Vivamus.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Cecilia', 'Nolan', '1988-09-01', NULL, NULL, 'aliquet@Suspendisse.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Uta', 'Juarez', '1989-09-08', NULL, NULL, 'Sed.pharetra.felis@in.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Dahlia', 'Walsh', '2005-03-26', NULL, NULL, 'pharetra.Nam@Phasellus.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Felix', 'Monroe', '1986-08-09', NULL, NULL, 'eu.elit@eueuismod.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Sylvester', 'Adkins', '2001-01-05', NULL, NULL, 'erat@turpisegestas.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Maxwell', 'Kane', '2003-05-13', NULL, NULL, 'cursus@inmagna.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Sylvester', 'Clarke', '1990-07-27', NULL, NULL, 'sem.ut@vitaemaurissit.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Diana', 'Parrish', '2001-07-19', NULL, NULL, 'risus@necmollis.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kyle', 'Levine', '1992-02-29', NULL, NULL, 'risus@aliquamadipiscing.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Jin', 'Gross', '1984-05-12', NULL, NULL, 'mollis@Duis.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Bert', 'Kent', '1998-09-22', NULL, NULL, 'Nunc.laoreet.lectus@aaliquet.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Shafira', 'Park', '1992-02-02', NULL, NULL, 'id@pede.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Timothy', 'Charles', '2004-04-29', NULL, NULL, 'sem@porttitor.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Summer', 'Santiago', '1997-05-29', NULL, NULL, 'arcu@tristique.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Lionel', 'Barrera', '2000-03-26', NULL, NULL, 'risus@dis.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Thaddeus', 'Roth', '2004-06-04', NULL, NULL, 'at.nisi.Cum@dui.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Rylee', 'Robertson', '1992-08-07', NULL, NULL, 'nonummy.ipsum.non@viverra.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Brenna', 'Roy', '1990-10-14', NULL, NULL, 'est@ut.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Finn', 'Walsh', '1998-03-06', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil7.jpg', 'ornare.libero.at@metusfacilisis.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 2);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Nelle', 'Berry', '1996-10-01', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil1.jpg', 'montes@hendreritaarcu.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 2);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kirk', 'Wagner', '1996-05-26', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore', 'profil2.jpg', 'purus.gravida.sagittis@tinciduntpedeac.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`FUNCTION_FSR`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Sprecher');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'stellv. Sprecher');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Finanzer');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'stellv. Finanzer');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Mitglied');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'inaktives Mitglied');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Social Media');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Lagerverwalter');

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`MEMBER_HISTORY`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-01-01', NULL, 1, 1);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-01-01', NULL, 2, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-01-01', '2019-06-01', 3, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 3, 2);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 4, 1);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 6, 3);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 7, 4);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-01-01', NULL, 109, 2);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 110, 4);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 111, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-01-01', NULL, 112, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 113, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 114, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 115, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 116, 4);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 117, 4);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 118, 4);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 119, 2);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 120, 3);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 121, 4);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 122, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 123, 3);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 124, 3);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 125, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 126, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 127, 5);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 128, 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`LOCATION`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`LOCATION` (`ID`, `CREATED_AT`, `UPDATED_AT`, `STREET`, `NUMBER`, `ZIPCODE`, `CITY`, `ROOM`) VALUES (DEFAULT, DEFAULT, NULL, 'Altonaerstrasse', '3', '99806', 'Erfurt', '3.1.23');
INSERT INTO `fsraiDatabase`.`LOCATION` (`ID`, `CREATED_AT`, `UPDATED_AT`, `STREET`, `NUMBER`, `ZIPCODE`, `CITY`, `ROOM`) VALUES (DEFAULT, DEFAULT, NULL, 'Altonaerstrasse', '3', '99080', 'Erfurt', '9.3.12');
INSERT INTO `fsraiDatabase`.`LOCATION` (`ID`, `CREATED_AT`, `UPDATED_AT`, `STREET`, `NUMBER`, `ZIPCODE`, `CITY`, `ROOM`) VALUES (DEFAULT, DEFAULT, NULL, 'Altonaerstrasse', '3', '88068', 'Erfurt', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`EVENT`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`EVENT` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`, `DATE`, `DESCRIPTION`, `PICTURE`, `LOCATION_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'HYE 2019', '2019-10-22', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'hye.jpg', 1);
INSERT INTO `fsraiDatabase`.`EVENT` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`, `DATE`, `DESCRIPTION`, `PICTURE`, `LOCATION_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Wintermarkt 2019', '2019-12-04', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'wintermarkt.jpg', 1);
INSERT INTO `fsraiDatabase`.`EVENT` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`, `DATE`, `DESCRIPTION`, `PICTURE`, `LOCATION_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Weihnachtsfeier 2019', '2019-12-11', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'weihnachtsfeier.jpg', 2);
INSERT INTO `fsraiDatabase`.`EVENT` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`, `DATE`, `DESCRIPTION`, `PICTURE`, `LOCATION_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Erstiewoche', '2019-06-11', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'erstie.jpg', 3);
INSERT INTO `fsraiDatabase`.`EVENT` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`, `DATE`, `DESCRIPTION`, `PICTURE`, `LOCATION_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Sommerfest', '2020-06-11', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'sommerfest.jpg', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`BOOKING`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`BOOKING` (`ID`, `CREATED_AT`, `UPDATED_AT`, `EVENT_ID`, `USER_ID`) VALUES (DEFAULT, DEFAULT, NULL, 1, 1);
INSERT INTO `fsraiDatabase`.`BOOKING` (`ID`, `CREATED_AT`, `UPDATED_AT`, `EVENT_ID`, `USER_ID`) VALUES (DEFAULT, DEFAULT, NULL, 1, 2);
INSERT INTO `fsraiDatabase`.`BOOKING` (`ID`, `CREATED_AT`, `UPDATED_AT`, `EVENT_ID`, `USER_ID`) VALUES (DEFAULT, DEFAULT, NULL, 3, 1);
INSERT INTO `fsraiDatabase`.`BOOKING` (`ID`, `CREATED_AT`, `UPDATED_AT`, `EVENT_ID`, `USER_ID`) VALUES (DEFAULT, DEFAULT, NULL, 2, 3);
INSERT INTO `fsraiDatabase`.`BOOKING` (`ID`, `CREATED_AT`, `UPDATED_AT`, `EVENT_ID`, `USER_ID`) VALUES (DEFAULT, DEFAULT, NULL, 2, 1);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
