-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 14:05:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fsraiDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fsraiDatabase` ;

-- -----------------------------------------------------
-- Schema fsraiDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fsraiDatabase` DEFAULT CHARACTER SET utf8 ;
USE `fsraiDatabase` ;

-- -----------------------------------------------------
-- Table `fsraiDatabase`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`ROLE` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`USER` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `DATE_OF_BIRTH` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `PICTURE` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_USER_ROLE1_idx` (`ROLE_ID` ASC),
  CONSTRAINT `fk_USER_ROLE1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `fsraiDatabase`.`ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`FUNCTION_FSR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`FUNCTION_FSR` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`FUNCTION_FSR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`MEMBER_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`MEMBER_HISTORY` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`MEMBER_HISTORY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `START_DATE` VARCHAR(45) NOT NULL,
  `END_DATE` VARCHAR(45) NULL,
  `MEMBER_ID` INT NOT NULL,
  `FUNCTION_FSR_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MEMBER_HISTORY_MEMBER1_idx` (`MEMBER_ID` ASC),
  INDEX `fk_MEMBER_HISTORY_FUNCTION_FSR1_idx` (`FUNCTION_FSR_ID` ASC),
  CONSTRAINT `fk_MEMBER_HISTORY_MEMBER1`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `fsraiDatabase`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEMBER_HISTORY_FUNCTION_FSR1`
    FOREIGN KEY (`FUNCTION_FSR_ID`)
    REFERENCES `fsraiDatabase`.`FUNCTION_FSR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`LOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`LOCATION` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`LOCATION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `STREET` VARCHAR(45) NOT NULL,
  `NUMBER` VARCHAR(45) NOT NULL,
  `ZIPCODE` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `ROOM` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`EVENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`EVENT` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`EVENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `NAME` VARCHAR(45) NOT NULL,
  `DATE` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  `PICTURE` VARCHAR(45) NULL,
  `LOCATION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_EVENTS_LOCATION1_idx` (`LOCATION_ID` ASC),
  CONSTRAINT `fk_EVENTS_LOCATION1`
    FOREIGN KEY (`LOCATION_ID`)
    REFERENCES `fsraiDatabase`.`LOCATION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `fsraiDatabase`.`BOOKING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsraiDatabase`.`BOOKING` ;

CREATE TABLE IF NOT EXISTS `fsraiDatabase`.`BOOKING` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `EVENTS_ID` INT NOT NULL,
  `MEMBER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_REGISTRATION_EVENTS1_idx` (`EVENTS_ID` ASC),
  INDEX `fk_REGISTRATION_MEMBER1_idx` (`MEMBER_ID` ASC),
  CONSTRAINT `fk_REGISTRATION_EVENTS1`
    FOREIGN KEY (`EVENTS_ID`)
    REFERENCES `fsraiDatabase`.`EVENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REGISTRATION_MEMBER1`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `fsraiDatabase`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`ROLE`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`ROLE` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (1, DEFAULT, NULL, 'Admin');
INSERT INTO `fsraiDatabase`.`ROLE` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (2, DEFAULT, NULL, 'Mitglied');
INSERT INTO `fsraiDatabase`.`ROLE` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (3, DEFAULT, NULL, 'Nutzer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (1, DEFAULT, NULL, 'Danny', 'Steinbrecher', '24.12.1989', 'Desc', NULL, 'danny.steinbrecher@fh-erfurt.de', '123456', 1);
INSERT INTO `fsraiDatabase`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (2, DEFAULT, NULL, 'Niclas', 'Jarowsky', '01.01.2000', 'Deafdjshfdgbv', NULL, 'niclas.jarowsky@fh-erfurt.de', '123456', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`FUNCTION_FSR`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (1, DEFAULT, NULL, 'Sprecher');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (2, DEFAULT, NULL, 'stellv. Sprecher');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (3, DEFAULT, NULL, 'Finanzer');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (4, DEFAULT, NULL, 'stellv. Finanzer');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (5, DEFAULT, NULL, 'Mitglied');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (6, DEFAULT, NULL, 'inaktives Mitglied');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (7, DEFAULT, NULL, 'Social Media');
INSERT INTO `fsraiDatabase`.`FUNCTION_FSR` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (8, DEFAULT, NULL, 'Lagerverwalter');

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`MEMBER_HISTORY`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (1, DEFAULT, NULL, '01.01.2018', NULL, 1, 1);
INSERT INTO `fsraiDatabase`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FSR_ID`) VALUES (2, DEFAULT, NULL, '01.01.2018', NULL, 2, 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`LOCATION`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`LOCATION` (`ID`, `CREATED_AT`, `UPDATED_AT`, `STREET`, `NUMBER`, `ZIPCODE`, `CITY`, `ROOM`) VALUES (1, DEFAULT, NULL, 'Altonaerstrasse', '3', '99806', 'Erfurt', '3.1.23');

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`EVENT`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`EVENT` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`, `DATE`, `DESCRIPTION`, `PICTURE`, `LOCATION_ID`) VALUES (1, DEFAULT, NULL, 'HYE 2019', '22.11.2019', 'Text', NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fsraiDatabase`.`BOOKING`
-- -----------------------------------------------------
START TRANSACTION;
USE `fsraiDatabase`;
INSERT INTO `fsraiDatabase`.`BOOKING` (`ID`, `CREATED_AT`, `UPDATED_AT`, `EVENTS_ID`, `MEMBER_ID`) VALUES (1, DEFAULT, NULL, 1, 1);
INSERT INTO `fsraiDatabase`.`BOOKING` (`ID`, `CREATED_AT`, `UPDATED_AT`, `EVENTS_ID`, `MEMBER_ID`) VALUES (2, DEFAULT, NULL, 1, 2);

COMMIT;

